{% set name = "dura" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tkellogg/dura/archive/v{{ version }}.tar.gz
  sha256: 6486afa167cc2c9b6b6646b9a3cb36e76c1a55e986f280607c8933a045d58cca

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - dura --help

about:
  home: https://github.com/tkellogg/dura
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Backs up your work automatically via Git commits
  dev_url: https://github.com/tkellogg/dura

extra:
  recipe-maintainers:
    - danielnachun
